import { MenuItem } from './menu.model';

export const MENU: MenuItem[] = [
  {
    id: 1,
    label: 'MENUITEMS.MENU.TEXT',
    icon: '',
    isCollapsed: true,
    link: '',
    subItems: [],
    isTitle: true,
    badge: null,
    parentId: 0,
    isLayout: false,
  },
  // {
  //   id: 4,
  //   label: 'MENUITEMS.EVENTS.TEXT',
  //   icon: 'ri-calendar-event-line',
  //   isCollapsed: true,
  //   link: '/events',
  //   subItems: [],
  //   isTitle: false,
  //   badge: null,
  //   parentId: 0,
  //   isLayout: false,
  // },
  // {
  //   id: 5,
  //   label: 'MENUITEMS.COUNTDOWN.TEXT',
  //   icon: 'ri-timer-line',
  //   isCollapsed: true,
  //   link: '/countdown-display',
  //   subItems: [],
  //   isTitle: false,
  //   badge: {
  //     variant: 'success',
  //     text: 'Display'
  //   },
  //   parentId: 0,
  //   isLayout: false,
  // },
  {
    id: 7,
    label: 'MENUITEMS.DASHBOARD_PAJAK.TEXT',
    icon: 'ri-dashboard-line',
    isCollapsed: true,
    link: '/dashboard-pajak',
    subItems: [],
    isTitle: false,
    badge: {
      variant: 'success',
      text: 'New'
    },
    parentId: 0,
    isLayout: false,
  },
  {
    id: 8,
    label: 'MENUITEMS.DASHBOARD_PENDAPATAN.TEXT',
    icon: 'ri-money-dollar-circle-line',
    isCollapsed: true,
    link: '/dashboard-pendapatan',
    subItems: [],
    isTitle: false,
    badge: {
      variant: 'warning',
      text: 'Target'
    },
    parentId: 0,
    isLayout: false,
  },
  {
    id: 6,
    label: 'MENUITEMS.BIDANG.TEXT',
    icon: 'ri-map-2-line',
    isCollapsed: true,
    link: '/bidang',
    subItems: [
      {
        id: 61,
        label: 'MENUITEMS.BIDANG.MAP.TEXT',
        icon: 'ri-map-pin-line',
        isCollapsed: true,
        link: '/bidang/map',
        subItems: [],
        isTitle: false,
        badge: null,
        parentId: 6,
        isLayout: false,
      },
      {
        id: 61,
        label: 'MENUITEMS.THEMATIC.MAP.TEXT',
        icon: 'ri-map-pin-line',
        isCollapsed: true,
        link: '/bidang/thematic-map',
        subItems: [],
        isTitle: false,
        badge: null,
        parentId: 6,
        isLayout: false,
      },
      {
        id: 62,
        label: 'MENUITEMS.BIDANG.LIST.TEXT',
        icon: 'ri-list-check-2',
        isCollapsed: true,
        link: '/bidang/list',
        subItems: [],
        isTitle: false,
        badge: null,
        parentId: 6,
        isLayout: false,
      }
    ],
    isTitle: false,
    badge: {
      variant: 'info',
      text: 'Geo'
    },
    parentId: 0,
    isLayout: false,
  },
  {
    id: 9,
    label: 'MENUITEMS.SETTING.TEXT',
    icon: 'ri-settings-3-line',
    isCollapsed: true,
    link: '/setting',
    subItems: [
      {
        id: 91,
        label: 'MENUITEMS.SETTING.KECAMATAN.TEXT',
        icon: 'ri-building-4-line',
        isCollapsed: true,
        link: '/setting/kecamatan',
        subItems: [],
        isTitle: false,
        badge: null,
        parentId: 9,
        isLayout: false,
      },
      {
        id: 92,
        label: 'MENUITEMS.SETTING.KELURAHAN.TEXT',
        icon: 'ri-community-line',
        isCollapsed: true,
        link: '/setting/kelurahan',
        subItems: [],
        isTitle: false,
        badge: null,
        parentId: 9,
        isLayout: false,
      },
      {
        id: 93,
        label: 'MENUITEMS.SETTING.BLOK.TEXT',
        icon: 'ri-grid-line',
        isCollapsed: true,
        link: '/setting/blok',
        subItems: [],
        isTitle: false,
        badge: null,
        parentId: 9,
        isLayout: false,
      }
    ],
    isTitle: false,
    badge: {
      variant: 'primary',
      text: 'Admin'
    },
    parentId: 0,
    isLayout: false,
  },
];

